### ISSUE TITLE
quit does not abort

### ISSUE THREAD

**Issue by dojeda** [gotcha/ipdb#111]
I hope I'm not the only one with this problem, but since I've upgraded to IPython 5, it is impossible to quit from a ipdb session, as before.

Here is a sample script:

``` python
def main():
    print('hello')
    while True:
        import ipdb; ipdb.set_trace()
        print('loop')

if __name__ == '__main__':
    main()
```

And a sample run:

```
python3 mwe.py
hello
> /home/dojeda/temp/mwe.py(5)main()
      3     while True:
      4         import ipdb; ipdb.set_trace()
----> 5         print('loop')
      6 
      7 if __name__ == '__main__':

ipdb> c
loop
> /home/dojeda/temp/mwe.py(4)main()
      2     print('hello')
      3     while True:
----> 4         import ipdb; ipdb.set_trace()
      5         print('loop')
      6 

ipdb> q
loop
> /home/dojeda/temp/mwe.py(5)main()
      3     while True:
      4         import ipdb; ipdb.set_trace()
----> 5         print('loop')
      6 
      7 if __name__ == '__main__':

ipdb> quit()
loop
> /home/dojeda/temp/mwe.py(4)main()
      2     print('hello')
      3     while True:
----> 4         import ipdb; ipdb.set_trace()
      5         print('loop')
      6 

ipdb> !!q
loop
> /home/dojeda/temp/mwe.py(5)main()
      3     while True:
      4         import ipdb; ipdb.set_trace()
----> 5         print('loop')
      6 
      7 if __name__ == '__main__':

ipdb> import sys; sys.exit(0)
*** SystemExit: 0
ipdb>
```

Version information:
ipdb==0.10.1
ipython==5.1.0

**Comment by ffeast** [comment]
Confirm. I've played a little bit with it, looks like the problem is with IPython, not ipdb.
When **IPython==5.1.0** is installed, neither ipdb version exits correctly. Tested with **0.8, 0.9, 0.10, 0.10.1**
However, the previous ipython version works fine, i.e. this configuration is ok:
```
$ pip freeze | egrep -i '^i'
ipdb==0.10.1
ipython==4.2.1
ipython-genutils==0.1.0
```

Also tested the **ipython==4.2.1** with **0.8** — all is fine

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

$ python -V
Python 2.7.6
```

All custom ipython settings were disabled during testing

**Comment by fvisin** [comment]
I can confirm the same occurs on Ubuntu 16.04 with ipython 5.1.0:
```
pip freeze | egrep -i '^i'
ipdb==0.8.1
ipython==5.1.0
ipython-genutils==0.1.0
```

**Comment by gerritholl** [comment]
Does anyone know a workaround for this problem, awaiting a fix?

**Comment by fvisin** [comment]
Downgrade to `ipython==5.0.0`

**Comment by abetkin** [comment]
Use `import os; os._exit()` as a workaround

**Comment by cmey** [comment]
Add to `~/.pdbrc` :
```
import os
alias kk os._exit(0)
```
then hit `kk` from inside an `ipdb` session, to exit.

**Comment by curiale** [comment]
Hi, 
Is there any news about this issue?

**Comment by meowsqueak** [comment]
How can we elevate the priority of this issue, or at least get it assigned to someone? It's a complete show-stopper and is hurting ipdb uptake.

**Comment by gnebehay** [comment]
After investigating the connections between ipdb and IPython a bit, I believe the best solution is to stop using ipdb and use the stand-alone debugger that comes with IPython. Documentation on this subject is extremely poor, but by replacing all calls to
```
import ipdb; ipdb.set_trace()
```
with
```
import IPython; IPython.terminal.debugger.TerminalPdb().set_trace()
```
you get all the functionality you are used to from ipdb. It seems that ipdb has always been just a very thin wrapper into IPython and the ipdb project itself seems obsolete to as of IPython 5.0.

**Comment by jgosmann** [comment]
@gnebehay Is there an equivalent for `python -m ipdb script.py`?

**Comment by gnebehay** [comment]
Nope, but I think you can reproduce the functionality quite easily by subclassing `TerminalPDB` and copy-pasting the main method from here with slight adaptions: https://github.com/gotcha/ipdb/blob/master/ipdb/__main__.py

**Comment by gnebehay** [comment]
After some more investigation, it turns out that this is actually an IPython issue. A fix is in the make for IPython 5.2. https://github.com/ipython/ipython/issues/10006

**Comment by joelostblom** [comment]
I believe you can close this issue as https://github.com/ipython/ipython/pull/10009 fixed the bug. I just upgraded from 5.1 to 5.3 and it is all good.

**Comment by dojeda** [comment]
@joelostblom Thanks for the heads up! 

Confirmed that Ipython==5.3 the issue is fixed:

```
$ python --version
Python 3.5.2
$ pip freeze | grep ipython\=
ipython==5.3.0
$ python mwe.py 
hello
> /home/dojeda/temp/mwe.py(5)main()
      3     while True:
      4         import ipdb; ipdb.set_trace()
----> 5         print('loop')
      6 
      7 if __name__ == '__main__':

ipdb> q
Exiting Debugger.
```

**Comment by operman18** [comment]
Hello, I have the exact ssame issue.When I run python2 code, i cannot exit the debugger.

`def main():
    print 'hello'
    while True:
        import ipdb; ipdb.set_trace()
        print('loop')

if __name__ == '__main__':
    main()
`
This outputs me when i try to exit:
`Post mortem debugger finished. The tmp.py will be restarted
Traceback (most recent call last):
  File "/home/operman/anaconda3/lib/python3.5/site-packages/ipdb/__main__.py", line 198, in main
    pdb._runscript(mainpyfile)
  File "/home/operman/anaconda3/lib/python3.5/pdb.py", line 1542, in _runscript
    self.run(statement)
  File "/home/operman/anaconda3/lib/python3.5/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/operman/bAbYCIM/networkGraph/tmp.py", line 2
    print 'hello'
                ^
SyntaxError: Missing parentheses in call to 'print'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> <string>(1)<module>()
`

**Comment by avatar-lavventura** [comment]
> alias kk os._exit(0)

Instead is it recommended to do `alias q os._exit(0)` , to overwrite `quit()` function keybinding?

**Comment by ssbarnea** [comment]
I wonder why after so many years we still do not have a default `q` that just works.

**Comment by ssbarnea** [comment]
@gotcha Good point! I would not making making a patch but I do not know exactly how to change ipdb code to make it do `os._exit(0)` when `q` is pressed. As a user, the alias works but the tricks is to make it do this without adding an alias. Doing a search for quite on the codebase did not uncover the code to patch. So, if someone could give few hints, i would not mind contributing a patch.
